/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mulacar.app;

import br.com.mulacar.bll.CidadeBll;
import br.com.mulacar.bll.ModeloBll;
import br.com.mulacar.model.Cidade;
import br.com.mulacar.model.Modelo;
import br.com.mulacar.util.EstadosEnum;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jsfr
 */
public class TelaCadastroAuxiliares extends javax.swing.JFrame {
    
    private DefaultTableModel modelo = new DefaultTableModel();
    CidadeBll cidadeBll = new CidadeBll();
    Cidade cidade = new Cidade();
    ModeloBll modeloBll = new ModeloBll();
    Modelo mod_veiculo = new Modelo();

    /**
     * Creates new form CadAuxDesk
     */
    public TelaCadastroAuxiliares() {
        CriartblDados();
        initComponents();


    }
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_nome = new javax.swing.JLabel();
        jTextField_nome = new javax.swing.JTextField();
        jButton_Excluir = new javax.swing.JButton();
        jButton_SalvarEditar = new javax.swing.JButton();
        jButton_limpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        model = new javax.swing.JTable();
        jLabel_estado = new javax.swing.JLabel();
        jCombo_estado = new javax.swing.JComboBox<>();
        jComboBox_TpCad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastros Auxiliares");

        jLabel_nome.setText("Nome:");

        jButton_Excluir.setText("Excluir");
        jButton_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExcluirActionPerformed(evt);
            }
        });

        jButton_SalvarEditar.setText("Salvar");
        jButton_SalvarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalvarEditarActionPerformed(evt);
            }
        });

        jButton_limpar.setText("Limpar");
        jButton_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limparActionPerformed(evt);
            }
        });

        model.setModel(modelo);
        model.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(model);

        jLabel_estado.setText("Estado:");

        jCombo_estado.setModel(new javax.swing.DefaultComboBoxModel(EstadosEnum.values()));

        jComboBox_TpCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Tipo Cadastro", "Cidade", "Marca", "Modelo" }));
        jComboBox_TpCad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_TpCadItemStateChanged(evt);
            }
        });
        jComboBox_TpCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_TpCadMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox_TpCadMouseExited(evt);
            }
        });
        jComboBox_TpCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TpCadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_SalvarEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Excluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_nome)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_estado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCombo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox_TpCad, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jComboBox_TpCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nome)
                    .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_estado)
                    .addComponent(jCombo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Excluir)
                    .addComponent(jButton_SalvarEditar)
                    .addComponent(jButton_limpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CriartblDados() {
       model = new JTable(modelo);
       modelo.addColumn("Código");
       modelo.addColumn("Nome");

       model.getColumnModel().getColumn(0).setPreferredWidth(10);
       model.getColumnModel().getColumn(1).setPreferredWidth(100);
       
    }
 
    private void ConsultarCidade() {
        System.out.println("estou na tela");
        modelo.setNumRows(0);
        List<Cidade> listaCidade = new ArrayList<Cidade>();

        listaCidade = cidadeBll.getConsulta();

        if (listaCidade.size() > 0) {

            for (int i = 0; i < listaCidade.size(); i++) {
                modelo.addRow(new Object[]{listaCidade.get(i).getIden(),
                    listaCidade.get(i).getNome(),});
            }

        } else {
            modelo.setNumRows(0);
        }

    }
    private void ConsultarModelo() {

        modelo.setNumRows(0);
        List<Modelo> listaModelo = new ArrayList<Modelo>();

        listaModelo = modeloBll.getConsulta();

        if (listaModelo.size() > 0) {

            for (int i = 0; i < listaModelo.size(); i++) {
                modelo.addRow(new Object[]{listaModelo.get(i).getModelo_iden(),
                    listaModelo.get(i).getNome(),});
            }

        } else {
            modelo.setNumRows(0);
        }

    }
    
    private void LimparCampos(){
        jTextField_nome.setText("");
        
    }
   
    private void PreencheCampos(int Iden) {
        if (Iden > 0) {
            switch (jComboBox_TpCad.getSelectedIndex()){
                
                case 1:
                    cidade = cidadeBll.getConsultaPorId(Iden);
                    jTextField_nome.setText(cidade.getNome());
                    jButton_SalvarEditar.setLabel("Editar");
                    break;
                    
                case 2:
                    mod_veiculo = modeloBll.getModeloById(Iden);
                    jTextField_nome.setText(mod_veiculo.getNome());
                    jButton_SalvarEditar.setLabel("Editar");
                    break;
                
                /*case 3:
                    tipo = tipoBll.getConsultaPorId(Iden);
                    jTextField_nome.setText(tipo.getNome());
                    jButton_SalvarEditar.setLabel("Editar");
                    break;*/
                default:
                    
            }
            
        } else {
            jButton_SalvarEditar.setLabel("Salvar");
        }
    }
    
    private void jButton_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExcluirActionPerformed
        // TODO add your handling code here:
        try{
            switch (jComboBox_TpCad.getSelectedIndex()){
                
                case 1:
                    cidadeBll.Remover(cidadeBll.getConsultaPorId(cidade.getIden()));
                    ConsultarCidade();
                    break;
                    
                case 2:
                    modeloBll.Remover(modeloBll.getModeloById(mod_veiculo.getModelo_iden()));
                    ConsultarModelo();
                    break;
                
                /*case 3:
                    tipoBll.Remover(tipoBll.getConsultaPorId(tipo.getId()));
                    ConsultarTipo();
                    break;*/
                default:
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção!!!", JOptionPane.INFORMATION_MESSAGE);
        }    
    }//GEN-LAST:event_jButton_ExcluirActionPerformed

    private void jButton_SalvarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalvarEditarActionPerformed
        // TODO add your handling code here:
        try {
            switch (jComboBox_TpCad.getSelectedIndex()){
                
                case 1:
                    
                    if (jButton_SalvarEditar.getLabel().equals("Salvar")) {
                        cidade.setNome(jTextField_nome.getText());
                        cidade.setEstado(EstadosEnum.valueOf(jCombo_estado.getSelectedItem().toString()));
                        cidadeBll.Adicionar(cidade);
                        
                    } else {
                        cidade.setNome(jTextField_nome.getText());
                        cidade.setEstado(EstadosEnum.valueOf(jCombo_estado.getSelectedItem().toString()));
                        cidadeBll.Alterar(cidade);
                    }
                    ConsultarCidade();
                    break;
                    
                case 2:
                    mod_veiculo.setNome(jTextField_nome.getText());
                    if (jButton_SalvarEditar.getLabel().equals("Salvar")) {
                        modeloBll.Adicionar(mod_veiculo);
                    } else {
                        modeloBll.Alterar(mod_veiculo);
                    }
                    ConsultarModelo();
                    break;
                    
             /*   case 3:
                    tipo.setNome(jTextField_nome.getText());
                    if (jButton_SalvarEditar.getLabel().equals("Salvar")) {
                        tipoBll.Adicionar(tipo);
                    } else {
                        tipoBll.Alterar(tipo);
                    }
                    ConsultarTipo();
                    break;*/
                default:
                }    
            LimparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção!!!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton_SalvarEditarActionPerformed

    private void jButton_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limparActionPerformed
        // TODO add your handling code here:
        LimparCampos();
        modelo.setNumRows(0);
        jComboBox_TpCad.setSelectedIndex(0);
    }//GEN-LAST:event_jButton_limparActionPerformed

    private void modelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modelMouseClicked
        // TODO add your handling code here:
        int linha = model.getSelectedRow();
        Integer codigo = (Integer) model.getValueAt(linha, 0);
        PreencheCampos((int) codigo);
    }//GEN-LAST:event_modelMouseClicked

    private void jComboBox_TpCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_TpCadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TpCadMouseClicked

    private void jComboBox_TpCadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_TpCadMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox_TpCadMouseExited

    private void jComboBox_TpCadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_TpCadItemStateChanged
        // TODO add your handling code here:
        if (jComboBox_TpCad.getSelectedIndex()==1){
            jLabel_estado.setEnabled(true);
            jCombo_estado.setEnabled(true);
            
        }
        else {
            jLabel_estado.setEnabled(false);
            jCombo_estado.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBox_TpCadItemStateChanged

    private void jComboBox_TpCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TpCadActionPerformed
        // TODO add your handling code here:
        
        //if(jComboBox_TpCad.getSelectedIndex()==2) ConsultarModelo();

    }//GEN-LAST:event_jComboBox_TpCadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAuxiliares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAuxiliares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAuxiliares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAuxiliares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroAuxiliares().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Excluir;
    private javax.swing.JButton jButton_SalvarEditar;
    private javax.swing.JButton jButton_limpar;
    private javax.swing.JComboBox<String> jComboBox_TpCad;
    private javax.swing.JComboBox<String> jCombo_estado;
    private javax.swing.JLabel jLabel_estado;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_nome;
    private javax.swing.JTable model;
    // End of variables declaration//GEN-END:variables
}
